### ISSUE TITLE
Css shenanigans

### ISSUE THREAD

**Issue by Kingproone** [LadybirdBrowser/ladybird.org#11]
<details>

<summary>fixed 1. the buttons touch when the screen is narrow enough</summary>

![Screenshot_20240707-132341_Mull](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/cb644ddd-1ae6-450d-ab49-c5091c3f98cc)

</details>

<details>

<summary>fixed 2. bottom links hang off the screen, when narrow</summary>

![Screenshot_20240707_132251](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/a52b1222-faad-4fb8-8451-8c32fe7dc26d)

</details>

<details>

<summary>fixed 3. the button is not centered vertically after "your email"</summary>

![Screenshot_20240707_132216](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/ee82cf62-033c-4f67-b08d-9357eb22040c)

</details>

<details>

<summary>4. you can zoom out on mobile</summary>

![Screenshot_20240707-132330_Mull](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/b092af4f-c1e2-4bbf-bdcd-235f7777e104)

</details>
<details>

<summary>4.1. on a phone</summary>

![Screenshot_20240709-101035_Mull](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/f6825b7e-6e54-4139-a0cd-851b96911f97)

</details>
<details>

<summary>4.2. in firefox</summary>

![Screenshot_20240709_101336](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/d776aa73-ae60-4aa8-97de-bf3b44ed9148)

</details>

After #18 both cases behave better.

5. The picture showcasing the browser doesn't reach the edge of the screen, like in proper wide mode. (pictures in 4.1 , 4.2)

<details>

<summary>fixed 6. The ladybird logo in the footer now aggressively fills any available space</summary>

![Screenshot_20240709_101739](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/4ae6c996-dd97-4746-a13a-366c7fdff15a)

</details>

**Comment by ADKaster** [comment]
item 4 is improved by #18, but not fully resolved

**Comment by Kingproone** [comment]
<details>

<summary>1. on a phone</summary>

![Screenshot_20240709-101035_Mull](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/f6825b7e-6e54-4139-a0cd-851b96911f97)

</details>
<details>

<summary>2. in firefox</summary>

![Screenshot_20240709_101336](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/d776aa73-ae60-4aa8-97de-bf3b44ed9148)

</details>

Both cases behave better, but now the picture showcasing the browser doesn't reach the edge of the screen, like in proper wide mode.

<details>

<summary>3. The ladybird logo in the footer now aggressively fills any available space</summary>

![Screenshot_20240709_101739](https://github.com/LadybirdBrowser/ladybird.org/assets/118820223/4ae6c996-dd97-4746-a13a-366c7fdff15a)

</details>

I'm impartial to how this looks compared to before, but a) was this intentional? and b) as the red lines _try_ to show, in my opinion it hangs off the bottom a bit compared to the links.

**Comment by versecafe** [comment]
1, 2, 3, & 6 are patched

**Comment by FMMazur** [comment]
Needs to fix the newsletter signup, with #21 it broke on mobile.

 <details>
<summary>on chromium</summary>
<img width="396" alt="image" src="https://github.com/LadybirdBrowser/ladybird.org/assets/36215582/a89f853d-2edf-480b-bb0d-15a032aee0f4">
</details>

 <details>
<summary>on a phone</summary>
<img width="396" src="https://github.com/LadybirdBrowser/ladybird.org/assets/36215582/163dcb01-35f3-4aad-8d5b-89cd2bbae93a" >
</details>

**Comment by versecafe** [comment]
@FMMazur Patched in PR 35

**Comment by FMMazur** [comment]
I was checking it out, it seems fine now, i do think the newsletter box and the links at the bottom needs some padding, like a px-4. @versecafe 

 <details>
<summary>from:</summary>
<img width="390" alt="image" src="https://github.com/LadybirdBrowser/ladybird.org/assets/36215582/773fc792-552d-43c9-9491-4e9d5b6f165b">
</details>
 <details>
<summary>to:</summary>
<img width="395" alt="image" src="https://github.com/LadybirdBrowser/ladybird.org/assets/36215582/2f9aaa1e-9031-4189-946f-c698c6e5f7ad">
</details>
