### ISSUE TITLE
Navigation entries "About", "News" and "Get Involved" are not clickable

### ISSUE THREAD

**Issue by simonkrauter** [LadybirdBrowser/ladybird.org#24]
Clicking on "Sponsors" scrolls the page down, but clicking the first 3 entries has no effect, even the cursor does not change to pointer.

Tested in Ladybird :), Chrome and Firefox.

**Investigation**

The inspector shows me, that div#header-blobs overlaps the navigation items.

![screenshot_firefox](https://github.com/LadybirdBrowser/ladybird.org/assets/8593614/1b0b0dc3-cf6f-42ff-99a5-83f02cd03cf8)

![screenshot_ladybird](https://github.com/LadybirdBrowser/ladybird.org/assets/8593614/c0622e69-d69c-481e-b3f1-25010c36f96f)

**Comment by Kingproone** [comment]
this is talking about the top navbar?
bc it is working for me

**Comment by simonkrauter** [comment]
Yes, the top bar.

**Comment by simonkrauter** [comment]
Update:
![Screenshot_2024-07-09_16-24-33](https://github.com/LadybirdBrowser/ladybird.org/assets/8593614/cdefbc6c-26b9-4c80-8779-18acfb3fdbba)

**Comment by simonkrauter** [comment]
Fixed by https://github.com/LadybirdBrowser/ladybird.org/pull/27
