### ISSUE TITLE
"Get Involved" button doesn't work on small screens

### ISSUE THREAD

**Issue by mrcolbyrussell** [LadybirdBrowser/ladybird.org#29]
1. Visit <https://ladybird.org/> in Chrome for Android, Firefox Mobile, or in Firefox's Responsive Design Mode set to e.g. "iPhone 12/13 Pro Max iOS 14.6"
2. Tap the "Get Involved" "button" (actually a link — an `a` element with class `btn` pointing to `/#gi`)

Expected results:

It's a working link that scrolls to "Get Involved" section

Actual results:

It doesn't.  Nothing happens.

Notes:

This is not the same as #24 and not fixed by #27.

Attachment:

![ladybird-dot-org-get-involved-button](https://github.com/LadybirdBrowser/ladybird.org/assets/126744954/6a83ccbc-05e7-4197-8a19-898f1a46ec43)

**Comment by versecafe** [comment]
#30 Resolves this

**Comment by versecafe** [comment]
Okay this needs some more work, the buttons work on narrow screens but specifically when in "mobile input" they aren't working even when at top layer this weird issue is likely baked into the CSS mess but that's getting pulled out over the week
