### ISSUE TITLE
Support IPv6 on Ladybird Homepage

### ISSUE THREAD

**Issue by xlmnxp** [LadybirdBrowser/ladybird.org#7]
Hello, I notice ladybird is IPv4-only

![image](https://github.com/LadybirdBrowser/ladybird.org/assets/20779154/f11e2982-fda1-41c8-a28b-c599b8cb9982)

I notice Ladybird.org use Github Pages and they support IPv6

just add the following `AAAA` records:
```
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153
```

Source: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by awesomekling** [comment]
DNS records updated, thanks for reporting :)

**Comment by xlmnxp** [comment]
@awesomekling thank you
